# docker compose with a network for running the 2 applications in subfolders : 
# - frontend/
# - backend/ 
#
version: '3.7'
services: 
  backend:
    build: ./backend
    image: backend
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    image: frontend
    ports:
      - "80:80"

