# Basic workflow to ensure the code shipped builds correctly

on:
  workflow_dispatch:
  push:
    paths: 
      - 'backend/**/*.java'
      - 'frontend/**/*.js'
  pull_request:
    types: [review_requested]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Build
      working-directory: ./backend
      run: mvn -B package --file pom.xml

  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
    - name: Build
      working-directory: ./frontend
      run: npm run build
